In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.Tensor(5, 3)
print (x)


1.00000e-19 *
  0.0000  0.0000  0.0000
  1.0842  0.0000 -0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
[torch.FloatTensor of size 5x3]



In [3]:
x = torch.rand(5, 3)
print (x)


 0.5811  0.7851  0.0684
 0.3020  0.2917  0.9906
 0.1316  0.5356  0.6016
 0.3098  0.2384  0.0823
 0.0954  0.5752  0.6333
[torch.FloatTensor of size 5x3]



In [4]:
print (x.size())

torch.Size([5, 3])


In [10]:
y = torch.rand(5, 3)
print (x + y)


 0.6010  1.0150  0.4374
 0.5807  0.6035  1.5028
 0.1836  1.1820  0.9158
 0.8815  0.3074  0.0873
 0.9040  1.3173  0.8392
[torch.FloatTensor of size 5x3]



In [11]:
print (torch.add(x, y))


 0.6010  1.0150  0.4374
 0.5807  0.6035  1.5028
 0.1836  1.1820  0.9158
 0.8815  0.3074  0.0873
 0.9040  1.3173  0.8392
[torch.FloatTensor of size 5x3]



In [12]:
result = torch.rand(5, 3)
torch.add(x, y, out=result)
print (result)


 0.6010  1.0150  0.4374
 0.5807  0.6035  1.5028
 0.1836  1.1820  0.9158
 0.8815  0.3074  0.0873
 0.9040  1.3173  0.8392
[torch.FloatTensor of size 5x3]



In [13]:
y.add_(x)
print (y)


 0.6010  1.0150  0.4374
 0.5807  0.6035  1.5028
 0.1836  1.1820  0.9158
 0.8815  0.3074  0.0873
 0.9040  1.3173  0.8392
[torch.FloatTensor of size 5x3]



In [16]:
print (result[:, 0])
print (result[1:3, 0:1])


 0.6010
 0.5807
 0.1836
 0.8815
 0.9040
[torch.FloatTensor of size 5]


 0.5807
 0.1836
[torch.FloatTensor of size 2x1]



In [19]:
x = torch.rand(3, 2)
y = x.view(6)
z = x.view(-1, 3)
print (x)
print (y)
print (z)


 0.5242  0.8820
 0.2529  0.4706
 0.9999  0.0275
[torch.FloatTensor of size 3x2]


 0.5242
 0.8820
 0.2529
 0.4706
 0.9999
 0.0275
[torch.FloatTensor of size 6]


 0.5242  0.8820  0.2529
 0.4706  0.9999  0.0275
[torch.FloatTensor of size 2x3]



In [22]:
a = torch.rand(3, 2)
b = torch.rand(5)

print (a)
print (b.size())

print (a.numpy())
print (b.numpy())


 0.2460  0.2445
 0.9773  0.1714
 0.4691  0.1179
[torch.FloatTensor of size 3x2]

torch.Size([5])
[[ 0.24597663  0.24450988]
 [ 0.97727615  0.17140907]
 [ 0.4691478   0.11789757]]
[ 0.98758769  0.62353951  0.06376743  0.41007596  0.43331307]


In [25]:
import numpy as np
a = np.ones(5)
c = np.ones((2, 2))
print (a)
print (c)
b = torch.from_numpy(a)
d = torch.from_numpy(c)
print (b)
print (b.size())
print (d)
print (d.size())

[ 1.  1.  1.  1.  1.]
[[ 1.  1.]
 [ 1.  1.]]

 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

torch.Size([5])

 1  1
 1  1
[torch.DoubleTensor of size 2x2]

torch.Size([2, 2])


In [ ]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    print (x+y)